---
- fail: msg="docker_ca_cert is undefined"
  when: docker_ca_cert == ''

- fail: msg="docker_tls_cert is undefined"
  when: docker_tls_cert == ''

- fail: msg="docker_tls_key is undefined"
  when: docker_tls_key == ''

- name: add yum repo
  copy: src=docker.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: install docker engine
  yum: name=docker-engine state=latest

- name: create docker TLS directory
  file: path=/root/.docker state=directory group=root owner=root mode=0700

- name: install docker TLS certificates
  template: src={{ item.from }} dest={{ item.to }} mode=0600
  with_items:
    - from: ca.pem.j2
      to: /root/.docker/ca.pem
    - from: cert.pem.j2
      to: /root/.docker/cert.pem
    - from: key.pem.j2
      to: /root/.docker/key.pem

- name: docker-py
  pip: name=docker-py state=latest

- name: stop running docker containers
  shell: docker stop $(docker ps -a -q) || true

- name: remove docker containers
  shell: docker rm -v $(docker ps -a -q) || true

- name: run docker cleanup cronjob
  cron: name="docker cleanup" minute=15 user="root" job="/usr/bin/docker rmi $(/usr/bin/docker images -q --filter 'dangling=true')"

- name: install docker-compose
  shell: curl -L https://github.com/docker/compose/releases/download/1.7.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose

- name: make docker-compose executable
  file: path=/usr/local/bin/docker-compose mode="u+x"

- name: set DOCKER_HOST
  lineinfile: dest=/etc/environment state=present line="DOCKER_HOST=tcp://{{ private_ip }}:2375"

- name: set DOCKER_TLS_VERIFY
  lineinfile: dest=/etc/environment state=present line="DOCKER_TLS_VERIFY=1"

- name: create a systemd directory
  file: path=/lib/systemd/system/docker.service.d state=directory

- name: copy systemd configuration file
  copy: src=docker-host.conf dest=/lib/systemd/system/docker.service.d/docker-host.conf

- name: stop docker daemon
  service: name=docker state=stopped

- name: Reload systemd
  command: systemctl daemon-reload

- name: start docker daemon
  service: name=docker state=started
